### ISSUE TITLE
make "git diff HEAD/--staged/origin" work

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/git-xltrail#10]
```
C:\Users\felix\DEV\xltrail-demo0>git diff HEAD
[6332] Failed to execute script git-xltrail-diff
Traceback (most recent call last):
  File "git-xltrail-diff.py", line 51, in <module>
  File "git-xltrail-diff.py", line 14, in get_vba
  File "site-packages\oletools\olevba3.py", line 2281, in __init__
  File "site-packages\oletools\thirdparty\olefile\olefile.py", line 508, in isOleFile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\dev\\null'
fatal: external diff died, stopping at Book1 - Copy.xlsm
```

**Comment by fzumstein** [comment]
fixed in 0.3.1
